### ISSUE TITLE
[morty] python3-requests: do_compile() error

### ISSUE THREAD

**Issue by zuka0828** [meta-debian/meta-debian#262]
Build conditions: Same as #256 

log.do_compile():

```
DEBUG: Executing shell function do_compile
ERROR: python3 setup.py build execution failed.
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import requests
  File "/home/deby/poky/build-mibs/tmp/work/i586-deby-linux/python3-requests/2.4.3-r0/git/requests/__init__.py", line 55, in <module>
    import urllib3
ImportError: No module named 'urllib3'
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at /home/deby/poky/build-mibs/tmp/work/i586-deby-linux/python3-requests/2.4.3-r0/temp/log.do_compile.444147)
```

**Comment by zuka0828** [comment]
Fixed by 6d968a13cf1b0961987a82128032223593f08197
