### ISSUE TITLE
[Bug]  Exception('DTB not found: %s, %s or %s' % cmds)

### ISSUE THREAD

**Issue by elfgoh** [meta-debian/meta-debian#77]
Following the build instructions in the README, I built using command `time bitbake core-image-minimal`. The build is successful. However there seems to be an issue running the built image. Any idea how to resolve this?

```
luther@debian:~/meta-debian/build$ runqemu qemuarm nographic bootparams="console=ttyAMA0"
runqemu - INFO - Assuming MACHINE = qemuarm
runqemu - INFO - Running MACHINE=qemuarm bitbake -e...
runqemu - INFO - MACHINE: qemuarm
runqemu - INFO - DEPLOY_DIR_IMAGE: /home/luther/meta-debian/build/tmp/deploy/images/qemuarm
runqemu - INFO - Running ls -t /home/luther/meta-debian/build/tmp/deploy/images/qemuarm/*.qemuboot.conf...
runqemu - INFO - CONFFILE: /home/luther/meta-debian/build/tmp/deploy/images/qemuarm/core-image-minimal-qemuarm-20171019140919.qemuboot.conf
Traceback (most recent call last):
  File "/home/luther/meta-debian/poky/scripts/runqemu", line 1041, in <module>
    ret = main()
  File "/home/luther/meta-debian/poky/scripts/runqemu", line 1029, in main
    config.check_and_set()
  File "/home/luther/meta-debian/poky/scripts/runqemu", line 562, in check_and_set
    self.check_kernel()
  File "/home/luther/meta-debian/poky/scripts/runqemu", line 503, in check_kernel
    raise Exception('DTB not found: %s, %s or %s' % cmds)
Exception: DTB not found: /home/luther/meta-debian/build/tmp/deploy/images/qemuarm/zImage-versatile-pb.dtb, /home/luther/meta-debian/build/tmp/deploy/images/qemuarm/zImage-versatile-pb.dtb* or /home/luther/meta-debian/build/tmp/deploy/images/qemuarm/*.dtb
luther@debian:~/meta-debian/build$
```

**Comment by dothanhtrung** [comment]
Hi elfgoh,

This issue now has been fixed at commit [3065169](https://github.com/meta-debian/meta-debian/commit/306516971111351aac713a31994272051a69297f). Please pull the new commit and re-build.

The cause of this issue is that DTB file is defined base on _PREFERRED_VERSION_linux-yocto_ while meta-debian uses _linux-base_ with different version.
```sh
(From meta/conf/machine/qemuarm.conf)
QB_DTB = "${@base_version_less_or_equal('PREFERRED_VERSION_linux-yocto', '4.7', '', 'zImage-versatile-pb.dtb', d)}"
```
On branch morty, PREFERRED_VERSION_linux-yocto is 4.8, then QB_DTB is "zImage-versatile-pb.dtb". However, linux-base's version is 4.4, so DTB file is not necessary and is not provided.

The fix overrides variable QB_DTB, so runqemu can work.
